### ISSUE TITLE
сетевая карта ловит глюк

### ISSUE THREAD

**Issue by msidog2** [opengs/itarmykit#27]
при выключении атаки и завершении работы программы. сетевая карта находится в шоковом состоянии и трафик нормально не проходит. сайты тупят, мессенджеры тоже. помогает только перезагрузка ПК

**Comment by opengs** [comment]
Не знаю чи зможу особливо вплинути на це з рівня тули. Який це був модуль? І чи ця проблема тільки з одним модулем чи зі всіма?

**Comment by msidog2** [comment]
> @msidog2 Не знаю чи зможу особливо вплинути на це з рівня тули. Який це був модуль? І чи ця проблема тільки з одним модулем чи зі всіма?

вроде в этой версии более менее стало норм. была проблема в mhdos

**Comment by opengs** [comment]
@msidog2 . звязався з розробником модуля. нажаль єдиний вихід це вибирати пресет послабіше / знижувати потужність. Бо і справді мережеву карту може перегрузити і буде лагати пк.

Ще перевірте ще раз чи все додано в виключення антивіруса. Бо якщо не додано то він буде коже запит перевіряти і лаги будуть страшні.

Більше нажаль допомогти не зможу бо проблема одинична. Якщо ще будуть зголошувати то будемо відкривати питання по новій.

Дякую за фідбек!
