### ISSUE TITLE
IT Army ID error

### ISSUE THREAD

**Issue by artemt1** [opengs/itarmykit#36]
![image](https://github.com/opengs/itarmykit/assets/29033930/984f2b2e-669b-43b3-a4c6-b34ca2e66cb9)

**Comment by yuraantonov11** [comment]
те ж саме в мене

**Comment by opengs** [comment]
Hi @yuraantonov11 @artemt1 . New APIKey was added to the ItArmy Bot and can be set in the settings. After adding APIKey to the settings, the problem will be resolved. This is not an error but rather information.

This error should be changed to "INFO" or something like this. I will probably do this during the nearest weekend when I will have time.

**Comment by artemt1** [comment]
Thanks for your reply. My next question is - what is this key used for and where to get it?

**Comment by opengs** [comment]
@artemt1 you can find APIKey in the ItArmy statistics bot (same place where is ITArmy ID). with APIKey, statistics will be shown directly inside the application

**Comment by opengs** [comment]
![image](https://github.com/opengs/itarmykit/assets/34212339/5b3d8748-72da-4b89-984d-bed766d2eb77)

Fixed in 1.3.1
